# Generated by Django 2.1.13 on 2019-10-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название для людей'),
        ),
    ]
