# Generated by Django 2.2.7 on 2019-12-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meta',
            options={'verbose_name': 'Мета теги', 'verbose_name_plural': 'Мета теги'},
        ),
    ]
