# Generated by Django 2.1.13 on 2019-10-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='Путь')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое файла')),
            ],
            options={
                'verbose_name': 'Файл подтвержения',
                'verbose_name_plural': 'Файлы подтверждения',
            },
        ),
    ]
