# Generated by Django 2.1.13 on 2019-10-31 16:23

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon', to='filer.File')),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконка',
            },
        ),
    ]
