# Generated by Django 2.2.7 on 2020-01-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favicon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favicon',
            options={'verbose_name': 'Favicon', 'verbose_name_plural': 'Faviconка'},
        ),
    ]
